// src/utils/preguntasEducar2026.js
// Preguntas basadas en la Prueba Evaluar - Corp Favorita 2026
// Estructura por módulos: Confiabilidad, Cognitivo, Conductual, DISC, EQ, Personalidad

export const ALL_QUESTIONS = [

  // ─────────────────────────────────────────────
  // MÓDULO 1: TEST DE CONFIABILIDAD
  // ─────────────────────────────────────────────
  {
    id: 1,
    text: '¿Me comprometo contestar con la verdad a todas las preguntas, y acepto que todas mis respuestas sean verificadas?',
    options: ['NO', 'SÍ'],
    correctIndex: 1,
    explanation: 'RESPUESTA = SÍ. Demuestras transparencia y disposición a ser evaluado con honestidad desde el inicio.',
  },
  {
    id: 2,
    text: 'Hemos notado una posible tendencia a presentar una imagen ideal de ti mismo(a). ¿Estás seguro(a) de estar respondiendo con total honestidad?',
    options: ['NO', 'SÍ'],
    correctIndex: 1,
    explanation: 'RESPUESTA = SÍ. Confirmar honestidad demuestra coherencia y transparencia ante el evaluador.',
  },

  // ─────────────────────────────────────────────
  // MÓDULO 2: TEST COGNITIVO
  // ─────────────────────────────────────────────
  {
    id: 3,
    text: 'Tomando en cuenta las siguientes afirmaciones: Primera: Carlos es mayor que Sofía. Segunda: Sofía es de la misma edad que Andrés. Última: Carlos es más viejo que Andrés. ¿Es la última afirmación verdadera o falsa?',
    options: ['Verdadero', 'Falso', 'No se puede determinar'],
    correctIndex: 0,
    explanation: 'RESPUESTA = VERDADERO. Proposición relacional: si A > B y B = C, entonces A > C. Carlos > Sofía = Andrés → Carlos > Andrés.',
  },
  {
    id: 4,
    text: '¿Cuál es la relación correcta entre las palabras "Libro" y "Libró"?',
    options: ['Son opuestos', 'Son semejantes', 'Ni opuestos ni semejantes — son parónimos'],
    correctIndex: 2,
    explanation: 'RESPUESTA = Ni opuestos ni semejantes. Son palabras parónimas (suenan parecido pero tienen distinto significado). Opuestos serían algo como frío-calor.',
  },

  // ─────────────────────────────────────────────
  // MÓDULO 3: CONDUCTUAL (ordenar comportamientos)
  // Instrucción: selecciona el orden CORRECTO empezando por el que MÁS se asemeja a la empresa.
  // La empresa busca: extroversión, servicio al cliente, trabajo en equipo, adaptabilidad, compromiso organizacional.
  // ─────────────────────────────────────────────
  {
    id: 5,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a trabajar en Corp Favorita:\nA) Soy servicial\nB) Soy persuasivo\nC) Prefiero los retos\nD) Comprendo el giro de negocio en mi trabajo',
    options: [
      'A → B → C → D (Servicial, Persuasivo, Retos, Negocio)',
      'A → D → C → B (Servicial, Negocio, Retos, Persuasivo)',
      'B → A → D → C (Persuasivo, Servicial, Negocio, Retos)',
      'D → A → B → C (Negocio, Servicial, Persuasivo, Retos)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → C → D. Primero lo más orientado al servicio, luego la capacidad de persuasión, después disposición al reto y por último conocimiento del negocio. La empresa prioriza servicio y calidez humana.',
  },
  {
    id: 6,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Me oriento a satisfacer a la gente\nB) Conozco los factores que influyen en mi trabajo\nC) Profundizo sobre la información que me han dado\nD) Utilizo tácticas para persuadir',
    options: [
      'A → B → C → D (Satisfacer gente, Conocer factores, Profundizar, Persuadir)',
      'D → A → C → B (Persuadir, Satisfacer, Profundizar, Conocer)',
      'B → C → A → D (Conocer, Profundizar, Satisfacer, Persuadir)',
      'C → A → D → B (Profundizar, Satisfacer, Persuadir, Conocer)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → C → D. La empresa quiere primero orientación a las personas (extroversión + servicio), luego responsabilidad y conocimiento, y al final persuasión (evita imagen de manipulador).',
  },
  {
    id: 7,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Tengo facilidad para relacionarme con otros\nB) Me intereso por los sentimientos de otros\nC) Practico los principios dispuestos en mi trabajo\nD) Modifico mis ideas si aparecen nuevas evidencias o datos',
    options: [
      'A → B → C → D (Relacionarme, Sentimientos, Principios, Cambio)',
      'C → A → B → D (Principios, Relacionarme, Sentimientos, Cambio)',
      'B → D → A → C (Sentimientos, Cambio, Relacionarme, Principios)',
      'D → C → B → A (Cambio, Principios, Sentimientos, Relacionarme)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → C → D. La extroversión y el relacionamiento van primero (son el perfil que busca la empresa), luego empatía, cumplimiento de normas y finalmente apertura al cambio.',
  },
  {
    id: 8,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) No me cuesta ser amable\nB) Me adapto eficazmente en diferentes circunstancias\nC) Me resulta fácil influir en los demás\nD) Me motiva la idea de aprender más\nE) Sonrío a menudo con la gente',
    options: [
      'A → E → C → B → D (Amable, Sonrío, Influir, Adaptar, Aprender)',
      'D → B → A → C → E (Aprender, Adaptar, Amable, Influir, Sonrío)',
      'C → A → B → E → D (Influir, Amable, Adaptar, Sonrío, Aprender)',
      'E → A → B → D → C (Sonrío, Amable, Adaptar, Aprender, Influir)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → E → C → B → D. Amabilidad y sonrisa reflejan el trato al cliente (perfil extrovertido que buscan), luego influencia, adaptabilidad y finalmente aprendizaje.',
  },
  {
    id: 9,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Encuentro metas y retos que puedo\nB) Soy examinador (ayuda a resolver problemas)\nC) Alineo mis metas con las de la organización\nD) Me oriento a satisfacer a la gente',
    options: [
      'D → C → A → B (Satisfacer gente, Alinear metas, Retos, Examinar)',
      'A → B → C → D (Retos, Examinar, Alinear, Satisfacer)',
      'C → D → B → A (Alinear, Satisfacer, Examinar, Retos)',
      'B → A → D → C (Examinar, Retos, Satisfacer, Alinear)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = D → C → A → B. Satisfacer a la gente es lo que más buscan, luego compromiso organizacional, luego disposición a retos y finalmente capacidad analítica.',
  },
  {
    id: 10,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Busco superar un estándar de excelencia\nB) Incentivo la participación de todos en el grupo\nC) Demuestro entusiasmo por aprender\nD) Oriento mis comportamientos en beneficio de mi trabajo',
    options: [
      'A → B → D → C (Excelencia, Participación grupal, Beneficio trabajo, Aprender)',
      'B → A → C → D (Participación, Excelencia, Aprender, Beneficio)',
      'D → C → B → A (Beneficio, Aprender, Participación, Excelencia)',
      'C → D → A → B (Aprender, Beneficio, Excelencia, Participación)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → D → C. Buscar la excelencia demuestra compromiso, luego el trabajo en equipo, luego orientación al trabajo y finalmente disposición a aprender.',
  },
  {
    id: 11,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Soy organizado y prolijo\nB) Evito reacciones exageradas que demuestran mi mal genio\nC) Obtengo información precisa de mis asuntos\nD) Creo mis propias oportunidades',
    options: [
      'A → B → C → D (Organizado, Control emocional, Información, Oportunidades)',
      'D → C → A → B (Oportunidades, Información, Organizado, Control)',
      'B → A → D → C (Control, Organizado, Oportunidades, Información)',
      'C → D → B → A (Información, Oportunidades, Control, Organizado)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → C → D. La organización y el autocontrol emocional son muy valorados en ambientes de servicio, luego la capacidad de información y la iniciativa.',
  },
  {
    id: 12,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Persisto en lo que me he propuesto\nB) Tengo capacidad para convencer e influir\nC) En condiciones de estrés mantengo mi eficacia laboral\nD) Propongo ideas nuevas',
    options: [
      'C → A → B → D (Eficacia bajo estrés, Persistencia, Influir, Ideas)',
      'D → B → A → C (Ideas, Influir, Persistencia, Eficacia)',
      'A → C → D → B (Persistencia, Eficacia, Ideas, Influir)',
      'B → D → C → A (Influir, Ideas, Eficacia, Persistencia)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = C → A → B → D. Mantener eficacia bajo estrés es clave en entornos de caja y servicio; la persistencia es valiosa, luego influencia y finalmente creatividad.',
  },
  {
    id: 13,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) No soy impulsivo ni nervioso\nB) Estoy abierto al cambio\nC) Mejoro y amplío mis conocimientos\nD) Al tomar decisiones tengo en cuenta las prioridades de la organización',
    options: [
      'A → D → B → C (Control emocional, Prioridades org., Cambio, Conocimiento)',
      'B → A → C → D (Cambio, Control, Conocimiento, Prioridades)',
      'D → C → A → B (Prioridades, Conocimiento, Control, Cambio)',
      'C → B → D → A (Conocimiento, Cambio, Prioridades, Control)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → D → B → C. El control emocional es muy valorado en atención al cliente; luego orientarse a los objetivos de la empresa, apertura al cambio y mejora continua.',
  },
  {
    id: 14,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Hago comentarios positivos sobre otros\nB) Promuevo la constancia para conseguir objetivos\nC) Soy propositivo (que propone)\nD) Oriento mis actividades en beneficio de mi trabajo',
    options: [
      'A → D → B → C (Positivo, Beneficio trabajo, Constancia, Propositivo)',
      'C → B → A → D (Propositivo, Constancia, Positivo, Beneficio)',
      'D → A → C → B (Beneficio, Positivo, Propositivo, Constancia)',
      'B → C → D → A (Constancia, Propositivo, Beneficio, Positivo)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → D → B → C. Hacer comentarios positivos refleja extroversión y buen trato; orientarse al trabajo muestra compromiso; la constancia y ser propositivo son complementos valiosos.',
  },
  {
    id: 15,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Estoy abierto a conversar con otros\nB) Brindo apoyo a otros\nC) Comprendo el funcionamiento de los productos y/o servicios de mi trabajo\nD) Insisto hasta lograr mis objetivos',
    options: [
      'A → B → C → D (Conversar, Apoyo, Conocimiento producto, Insistencia)',
      'D → C → B → A (Insistencia, Conocimiento, Apoyo, Conversar)',
      'B → A → D → C (Apoyo, Conversar, Insistencia, Conocimiento)',
      'C → D → A → B (Conocimiento, Insistencia, Conversar, Apoyo)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → C → D. La apertura a conversar refleja extroversión (lo más buscado), luego apoyo (trabajo en equipo), conocimiento del producto y finalmente persistencia.',
  },
  {
    id: 16,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Tengo vocación para servir bien al cliente\nB) Respondo positivamente a los cambios del entorno\nC) Motivo para que se cumplan las metas grupales\nD) Me impongo mis propias metas',
    options: [
      'A → C → B → D (Servicio cliente, Metas grupales, Cambio, Metas propias)',
      'D → B → C → A (Metas propias, Cambio, Metas grupales, Servicio)',
      'C → A → D → B (Metas grupales, Servicio, Metas propias, Cambio)',
      'B → D → A → C (Cambio, Metas propias, Servicio, Metas grupales)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → C → B → D. La vocación de servicio es el perfil más buscado en Corp Favorita; luego trabajo en equipo, adaptación al cambio y finalmente autonomía personal.',
  },
  {
    id: 17,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Me interesa relacionarme con los demás\nB) Me adapto a los cambios en mi trabajo\nC) Entiendo la estructura de la empresa\nD) Promuevo la calma a otros',
    options: [
      'A → D → B → C (Relacionarme, Calma, Adaptación, Estructura)',
      'C → B → A → D (Estructura, Adaptación, Relacionarme, Calma)',
      'B → A → D → C (Adaptación, Relacionarme, Calma, Estructura)',
      'D → C → A → B (Calma, Estructura, Relacionarme, Adaptación)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → D → B → C. Relacionarse con los demás es la extroversión que busca la empresa; promover calma es manejo emocional valorado en caja; luego adaptabilidad y conocimiento organizacional.',
  },
  {
    id: 18,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Soy atento con los demás\nB) Mis resultados exceden las expectativas\nC) Analizo los detalles sin perder de vista el todo\nD) Archivo y documento mis cosas',
    options: [
      'A → B → C → D (Atención, Resultados, Análisis, Documentación)',
      'D → C → B → A (Documentación, Análisis, Resultados, Atención)',
      'B → A → D → C (Resultados, Atención, Documentación, Análisis)',
      'C → D → A → B (Análisis, Documentación, Atención, Resultados)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → C → D. La atención a los demás refleja el perfil de servicio; superar expectativas muestra compromiso; el análisis y documentación son habilidades de apoyo.',
  },
  {
    id: 19,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Tengo tacto al hablar con las personas\nB) Ante una situación hostil me controlo\nC) Mi trabajo denota superación constante\nD) Busco activamente información para realizar mi trabajo',
    options: [
      'A → B → C → D (Tacto, Control, Superación, Información)',
      'D → C → B → A (Información, Superación, Control, Tacto)',
      'C → A → D → B (Superación, Tacto, Información, Control)',
      'B → D → A → C (Control, Información, Tacto, Superación)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → C → D. El tacto en la comunicación es extroversión aplicada al servicio; el autocontrol es clave en atención al cliente; la superación y la búsqueda de información son complementos.',
  },
  {
    id: 20,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Tengo confianza en mí mismo\nB) Descompongo problemas en partes pequeñas\nC) Escucho las opiniones de todos en mi grupo\nD) Deseo poseer más información',
    options: [
      'A → C → B → D (Confianza, Escucha grupal, Análisis, Información)',
      'D → B → A → C (Información, Análisis, Confianza, Escucha)',
      'C → A → D → B (Escucha, Confianza, Información, Análisis)',
      'B → D → C → A (Análisis, Información, Escucha, Confianza)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → C → B → D. La confianza en sí mismo es clave para el trato al cliente; escuchar al grupo refleja trabajo en equipo; luego habilidades analíticas y curiosidad de información.',
  },
  {
    id: 21,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Prefiero un trabajo que me relacione con gente\nB) Comprendo las situaciones de forma sistemática\nC) Antepongo las metas grupales sobre las personales\nD) Busco mi propia capacitación personal',
    options: [
      'A → C → B → D (Relacionarme con gente, Metas grupales, Sistemático, Capacitación)',
      'D → A → C → B (Capacitación, Relacionarme, Metas grupales, Sistemático)',
      'C → B → D → A (Metas grupales, Sistemático, Capacitación, Relacionarme)',
      'B → D → A → C (Sistemático, Capacitación, Relacionarme, Metas grupales)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → C → B → D. Preferir trabajar con gente es el perfil extrovertido ideal; anteponer metas grupales muestra trabajo en equipo; luego pensamiento sistemático y autocapacitación.',
  },
  {
    id: 22,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Mis emociones están bajo control\nB) Soy decidido\nC) Encuentro soluciones con facilidad\nD) Comprendo las políticas y prioridades del negocio',
    options: [
      'A → D → B → C (Control emocional, Políticas negocio, Decisión, Soluciones)',
      'C → B → D → A (Soluciones, Decisión, Políticas, Control)',
      'B → A → C → D (Decisión, Control, Soluciones, Políticas)',
      'D → C → A → B (Políticas, Soluciones, Control, Decisión)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → D → B → C. El control emocional es fundamental en caja y atención al cliente; conocer las políticas muestra compromiso organizacional; la decisión y resolución son complementos.',
  },
  {
    id: 23,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Ayudo a mis compañeros de trabajo\nB) Antepongo intereses organizacionales sobre los personales\nC) Me reconocen como emprendedor\nD) Considero que tengo alta energía',
    options: [
      'A → B → D → C (Ayudar, Intereses org., Alta energía, Emprendedor)',
      'D → C → A → B (Alta energía, Emprendedor, Ayudar, Intereses org.)',
      'B → A → C → D (Intereses org., Ayudar, Emprendedor, Alta energía)',
      'C → D → B → A (Emprendedor, Alta energía, Intereses org., Ayudar)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → D → C. Ayudar a compañeros refleja trabajo en equipo; anteponer intereses organizacionales muestra lealtad; la energía y el emprendimiento son rasgos de apoyo.',
  },
  {
    id: 24,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Sé cómo tratar a la gente\nB) Sé controlarme aun en momentos de tensión\nC) Poseo capacidad de automotivación\nD) Entiendo la dinámica de las empresas',
    options: [
      'A → B → D → C (Tratar gente, Control tensión, Dinámica empresas, Automotivación)',
      'C → A → D → B (Automotivación, Tratar gente, Dinámica, Control)',
      'D → C → A → B (Dinámica, Automotivación, Tratar gente, Control)',
      'B → D → C → A (Control, Dinámica, Automotivación, Tratar gente)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → D → C. Saber tratar a la gente es el perfil de servicio extrovertido; el control en tensión es clave; entender la empresa muestra compromiso; la automotivación cierra.',
  },
  {
    id: 25,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Soy ordenado\nB) Tomo la iniciativa\nC) Comprendo la misión/visión en mi trabajo\nD) Actúo coherentemente con los objetivos de la empresa',
    options: [
      'D → C → B → A (Objetivos empresa, Misión/visión, Iniciativa, Orden)',
      'A → B → C → D (Orden, Iniciativa, Misión, Objetivos)',
      'B → A → D → C (Iniciativa, Orden, Objetivos, Misión)',
      'C → D → A → B (Misión, Objetivos, Orden, Iniciativa)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = D → C → B → A. Actuar alineado con los objetivos y conocer la misión demuestra compromiso organizacional; la iniciativa y el orden son rasgos personales de apoyo.',
  },
  {
    id: 26,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Interpreto el lenguaje corporal\nB) Estoy convencido de mis capacidades\nC) Me propongo metas altas pero factibles\nD) Mis actividades las realizo en equipo',
    options: [
      'D → B → C → A (Equipo, Confianza, Metas, Lenguaje corporal)',
      'A → C → B → D (Lenguaje, Metas, Confianza, Equipo)',
      'C → A → D → B (Metas, Lenguaje, Equipo, Confianza)',
      'B → D → A → C (Confianza, Equipo, Lenguaje, Metas)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = D → B → C → A. Trabajar en equipo es lo más valorado en Corp Favorita; la confianza refleja seguridad en el trato; las metas muestran compromiso y el lenguaje corporal es una habilidad interpersonal adicional.',
  },
  {
    id: 27,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Soy expresivo\nB) Tengo aptitudes para lograr lo que me propongo\nC) Influyo en los pensamientos de otros\nD) Soy excelente buscando información',
    options: [
      'A → C → B → D (Expresivo, Influencia, Aptitudes, Información)',
      'D → B → A → C (Información, Aptitudes, Expresivo, Influencia)',
      'C → A → D → B (Influencia, Expresivo, Información, Aptitudes)',
      'B → D → C → A (Aptitudes, Información, Influencia, Expresivo)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → C → B → D. Ser expresivo refleja extroversión ideal para atención al cliente; influir en otros es habilidad social valorada; las aptitudes y la búsqueda de información son complementos.',
  },
  {
    id: 28,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Deseo ayudar a la gente\nB) Tengo energía para hacer mis cosas\nC) Sigo un orden en el trabajo\nD) Pienso sobre asuntos complejos en forma analítica',
    options: [
      'A → B → C → D (Ayudar, Energía, Orden, Analítico)',
      'D → C → B → A (Analítico, Orden, Energía, Ayudar)',
      'C → A → D → B (Orden, Ayudar, Analítico, Energía)',
      'B → D → A → C (Energía, Analítico, Ayudar, Orden)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → C → D. Desear ayudar es el perfil de servicio extrovertido; la energía es positiva para el trabajo presencial; el orden y el pensamiento analítico son habilidades de apoyo.',
  },
  {
    id: 29,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) En situaciones de presión mantengo la calma\nB) Tengo seguridad de mí mismo\nC) Me esfuerzo por lograr las metas de mi equipo de trabajo\nD) Contacto a fuentes claves para obtener información',
    options: [
      'A → C → B → D (Calma bajo presión, Metas equipo, Seguridad, Información)',
      'D → B → A → C (Información, Seguridad, Calma, Metas equipo)',
      'C → A → D → B (Metas equipo, Calma, Información, Seguridad)',
      'B → D → C → A (Seguridad, Información, Metas equipo, Calma)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → C → B → D. Mantener la calma bajo presión es esencial en caja; esforzarse por las metas del equipo muestra trabajo colaborativo; la seguridad personal y la búsqueda de información son complementos.',
  },
  {
    id: 30,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Soy perseverante\nB) Promuevo los objetivos de la empresa en el trabajo\nC) Me actualizo (en conocimientos) constantemente\nD) Soy investigativo',
    options: [
      'B → A → C → D (Objetivos empresa, Perseverancia, Actualización, Investigativo)',
      'D → C → B → A (Investigativo, Actualización, Objetivos, Perseverancia)',
      'A → D → C → B (Perseverancia, Investigativo, Actualización, Objetivos)',
      'C → B → A → D (Actualización, Objetivos, Perseverancia, Investigativo)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = B → A → C → D. Promover los objetivos de la empresa muestra compromiso organizacional (muy valorado); la perseverancia refleja constancia; actualizarse y ser investigativo son habilidades de crecimiento.',
  },
  {
    id: 31,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Poseo suficiente autoconfianza\nB) Exploro más de lo que me enseñan\nC) Tengo poder de convencimiento\nD) Realizo sugerencias constructivas orientadas a mejorar el bienestar de la organización',
    options: [
      'A → C → D → B (Autoconfianza, Convencimiento, Sugerencias org., Explorar)',
      'B → D → A → C (Explorar, Sugerencias, Autoconfianza, Convencimiento)',
      'D → A → C → B (Sugerencias, Autoconfianza, Convencimiento, Explorar)',
      'C → B → D → A (Convencimiento, Explorar, Sugerencias, Autoconfianza)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → C → D → B. La autoconfianza facilita el trato con clientes; el poder de convencimiento es habilidad interpersonal clave; las sugerencias organizacionales muestran compromiso y explorar el conocimiento es un plus.',
  },
  {
    id: 32,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Comprendo el sentir de los demás\nB) Soy controlado y calmado\nC) Me esfuerzo por mi crecimiento profesional\nD) Obtengo información de fuentes claves',
    options: [
      'A → B → C → D (Empatía, Control, Crecimiento, Información)',
      'D → C → B → A (Información, Crecimiento, Control, Empatía)',
      'B → A → D → C (Control, Empatía, Información, Crecimiento)',
      'C → D → A → B (Crecimiento, Información, Empatía, Control)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → C → D. Comprender el sentir de los demás es empatía orientada al cliente; el control y la calma son esenciales en atención; el crecimiento profesional y la gestión de información complementan.',
  },
  {
    id: 33,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Me gusta ayudar por aprender nuevas cosas\nB) Me adapto con facilidad a los cambios\nC) Me esfuerzo por aprender nuevas cosas\nD) Apoyo decisiones de la empresa',
    options: [
      'D → B → A → C (Apoyo empresa, Adaptación, Ayudar/aprender, Aprender)',
      'A → C → B → D (Ayudar/aprender, Aprender, Adaptación, Apoyo empresa)',
      'C → A → D → B (Aprender, Ayudar/aprender, Apoyo empresa, Adaptación)',
      'B → D → C → A (Adaptación, Apoyo empresa, Aprender, Ayudar/aprender)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = D → B → A → C. Apoyar decisiones de la empresa refleja compromiso organizacional; la adaptabilidad es muy valorada; ayudar motivado por el aprendizaje y seguir aprendiendo son rasgos positivos de crecimiento.',
  },
  {
    id: 34,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Me reconocen como amable\nB) Fomento el espíritu de equipo\nC) Busco formas nuevas de hacer las cosas\nD) Expreso mi orgullo por pertenecer a la empresa',
    options: [
      'A → B → D → C (Amable, Equipo, Orgullo empresa, Innovación)',
      'D → C → A → B (Orgullo, Innovación, Amable, Equipo)',
      'B → A → C → D (Equipo, Amable, Innovación, Orgullo)',
      'C → D → B → A (Innovación, Orgullo, Equipo, Amable)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → D → C. Ser reconocido como amable es el perfil extrovertido de servicio; fomentar el equipo es trabajo colaborativo; el orgullo organizacional muestra lealtad; la innovación es un plus.',
  },
  {
    id: 35,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Ayudo al cliente a concretar su requerimiento\nB) Colaboro activamente en un equipo\nC) Me interesa aprender más para mejorar mi trabajo\nD) Descubro nuevos datos y documentos',
    options: [
      'A → B → C → D (Ayudar cliente, Equipo, Aprender, Descubrir info)',
      'D → C → B → A (Descubrir, Aprender, Equipo, Ayudar)',
      'B → A → D → C (Equipo, Ayudar, Descubrir, Aprender)',
      'C → D → A → B (Aprender, Descubrir, Ayudar, Equipo)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → C → D. Ayudar al cliente a concretar su requerimiento es el comportamiento más alineado con el perfil de servicio de Corp Favorita; luego trabajo en equipo, aprendizaje continuo y gestión de información.',
  },
  {
    id: 36,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Soy autoexigente y disciplinado\nB) Tengo ordenado mi lugar de trabajo\nC) Promuevo la formación de equipos de trabajo\nD) Comprendo la relación que existe entre los departamentos de mi trabajo',
    options: [
      'C → A → D → B (Equipo, Autoexigencia, Estructura org., Orden)',
      'A → B → C → D (Autoexigencia, Orden, Equipo, Estructura)',
      'D → C → B → A (Estructura, Equipo, Orden, Autoexigencia)',
      'B → D → A → C (Orden, Estructura, Autoexigencia, Equipo)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = C → A → D → B. Promover equipos refleja trabajo colaborativo y extroversión; la autoexigencia muestra compromiso; entender la estructura departamental es conocimiento organizacional; el orden es complemento.',
  },
  {
    id: 37,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Escucho atentamente a los otros\nB) Trabajo con orden y calidad\nC) La perseverancia me hace lograr cosas\nD) Motivo a mis compañeros al compromiso organizacional',
    options: [
      'A → D → C → B (Escucha, Motivar compromiso, Perseverancia, Orden)',
      'B → C → A → D (Orden, Perseverancia, Escucha, Motivar)',
      'D → A → B → C (Motivar, Escucha, Orden, Perseverancia)',
      'C → B → D → A (Perseverancia, Orden, Motivar, Escucha)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → D → C → B. Escuchar atentamente es empatía orientada al servicio; motivar al compromiso organizacional refleja liderazgo y lealtad; la perseverancia y el orden son habilidades de apoyo.',
  },
  {
    id: 38,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Tengo energía para ser constante\nB) Los cambios son oportunidades para aprender y crecer\nC) Tengo pensamiento analítico para solucionar errores\nD) Convenzo al grupo para trabajar por objetivos',
    options: [
      'D → A → B → C (Convencer grupo, Energía, Cambio=oportunidad, Analítico)',
      'A → C → D → B (Energía, Analítico, Convencer, Cambio)',
      'B → D → C → A (Cambio, Convencer, Analítico, Energía)',
      'C → B → A → D (Analítico, Cambio, Energía, Convencer)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = D → A → B → C. Convencer al grupo para trabajar por objetivos es liderazgo orientado al equipo; la energía constante es positiva en entornos de caja; ver el cambio como oportunidad muestra adaptabilidad; el análisis cierra.',
  },
  {
    id: 39,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Motivo el diálogo con la gente\nB) Prefiero trabajar en grupo\nC) Alcanzo lo que me he propuesto\nD) Actúo en beneficio de la organización',
    options: [
      'A → B → D → C (Diálogo, Grupo, Beneficio org., Lograr metas)',
      'D → C → A → B (Beneficio org., Lograr metas, Diálogo, Grupo)',
      'B → A → C → D (Grupo, Diálogo, Lograr metas, Beneficio org.)',
      'C → D → B → A (Lograr metas, Beneficio org., Grupo, Diálogo)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → D → C. Motivar el diálogo es extroversión en su máxima expresión; trabajar en grupo refleja colaboración; actuar en beneficio de la organización muestra compromiso; alcanzar metas es el cierre de los anteriores.',
  },
  {
    id: 40,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Me esfuerzo por entender a los demás\nB) Aporto con todo lo necesario cuando trabajo en equipo\nC) Actúo con tenacidad y constancia\nD) Soluciono las cosas con lógica',
    options: [
      'A → B → C → D (Entender a otros, Aporte en equipo, Tenacidad, Lógica)',
      'D → C → A → B (Lógica, Tenacidad, Entender, Aporte)',
      'B → A → D → C (Aporte, Entender, Lógica, Tenacidad)',
      'C → D → B → A (Tenacidad, Lógica, Aporte, Entender)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → C → D. Entender a los demás es empatía y extroversión; aportar en equipo es colaboración; la tenacidad muestra constancia y la lógica es una habilidad de apoyo para resolución.',
  },
  {
    id: 41,
    text: 'Ordena los comportamientos empezando por el que MÁS se asemeje a lo que busca Corp Favorita:\nA) Tengo la habilidad de controlarme\nB) Aprovecho la mínima oportunidad para aprender algo nuevo\nC) Estoy feliz de ser yo mismo\nD) Mis objetivos son claros y alcanzables',
    options: [
      'A → C → D → B (Control, Autoaceptación, Objetivos claros, Aprendizaje)',
      'B → D → C → A (Aprendizaje, Objetivos, Autoaceptación, Control)',
      'C → A → B → D (Autoaceptación, Control, Aprendizaje, Objetivos)',
      'D → B → A → C (Objetivos, Aprendizaje, Control, Autoaceptación)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → C → D → B. El autocontrol es fundamental en caja y atención al cliente; la autoaceptación refleja estabilidad emocional; los objetivos claros muestran orientación al logro; aprovechar cada oportunidad de aprendizaje es la actitud de crecimiento.',
  },

  // ─────────────────────────────────────────────
  // MÓDULO 4: DISC
  // ─────────────────────────────────────────────
  {
    id: 42,
    text: '¿Qué palabras te describen dentro del trabajo? (selecciona las que más se ajusten al perfil de Corp Favorita — grupo 1)',
    options: [
      'Influyente, Autocontrolado, Disciplinado, Independiente, Cuestionador',
      'Influyente, Cuestionador, Independiente, Autocontrolado, Disciplinado',
      'Independiente, Disciplinado, Cuestionador, Influyente, Autocontrolado',
      'Disciplinado, Independiente, Autocontrolado, Cuestionador, Influyente',
    ],
    correctIndex: 0,
    explanation: 'Se busca el conjunto: Influyente (I), Autocontrolado (S/C), Disciplinado (C), reflejan el perfil de servicio con estabilidad. El orden importa: primero lo social/extrovertido, luego lo estructurado.',
  },
  {
    id: 43,
    text: '¿Qué palabras te describen dentro del trabajo? (selecciona las que más se ajusten al perfil de Corp Favorita — grupo 2)',
    options: [
      'Busca resultados, Espontáneo, Insistente, Cumplido, Obediente',
      'Obediente, Cumplido, Busca resultados, Insistente, Espontáneo',
      'Insistente, Obediente, Espontáneo, Cumplido, Busca resultados',
      'Cumplido, Busca resultados, Obediente, Espontáneo, Insistente',
    ],
    correctIndex: 0,
    explanation: 'Buscar resultados (D), ser espontáneo (I), insistente (D), cumplido (C) y obediente (S/C) reflejan el balance DISC que valora Corp Favorita: orientación al logro con cumplimiento de normas.',
  },
  {
    id: 44,
    text: '¿Qué palabras te describen dentro del trabajo? (selecciona las que más se ajusten al perfil de Corp Favorita — Extrovertido)',
    options: [
      'Extrovertido, Cooperador, Enérgico, Equilibrado, Dispuesto',
      'Cooperador, Equilibrado, Extrovertido, Dispuesto, Enérgico',
      'Enérgico, Dispuesto, Cooperador, Extrovertido, Equilibrado',
      'Equilibrado, Extrovertido, Dispuesto, Enérgico, Cooperador',
    ],
    correctIndex: 0,
    explanation: 'Extrovertido, cooperador, enérgico, equilibrado y dispuesto son exactamente el perfil I/S que busca Corp Favorita: sociable, colaborativo y con buena disposición para el servicio.',
  },
  {
    id: 45,
    text: 'En el módulo DISC, ¿qué deben reflejar las palabras que eliges en la segunda ronda (lo que piensan tus compañeros sobre ti)?',
    options: [
      'Deben ser completamente diferentes a las que elegiste para ti mismo',
      'Deben ser similares o iguales a las que elegiste para ti mismo',
      'Deben ser lo opuesto para mostrar equilibrio',
      'No importa el orden, solo que sean positivas',
    ],
    correctIndex: 1,
    explanation: 'RESPUESTA = Similares o iguales. La coherencia entre cómo te ves y cómo te ven los demás refleja autenticidad y consistencia de carácter. Una discrepancia grande puede generar dudas.',
  },

  // ─────────────────────────────────────────────
  // MÓDULO 5: EQ (Cociente Emocional)
  // ─────────────────────────────────────────────
  {
    id: 46,
    text: 'Ordena los comportamientos EQ empezando por el que MÁS se asemeje a tu manera de actuar (bloque 1):\nA) Me es fácil escoger la mejor solución cuando tengo que resolver un problema\nB) Puedo controlar mis impulsos en situaciones adversas\nC) Cuando estoy enojado con alguien se lo puedo decir\nD) Me resulta fácil expresar mis sentimientos\nE) Soy una persona divertida',
    options: [
      'B → D → C → E → A (Control impulsos, Expresar sentimientos, Decir enojo, Divertido, Resolver problemas)',
      'A → B → C → D → E (Resolver, Control, Decir, Expresar, Divertido)',
      'E → C → D → B → A (Divertido, Decir, Expresar, Control, Resolver)',
      'D → E → B → A → C (Expresar, Divertido, Control, Resolver, Decir)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = B → D → C → E → A. El autocontrol es lo más valorado en entornos de servicio al cliente; expresar sentimientos y comunicarlos asertivamente muestran madurez emocional; ser divertido refleja extroversión.',
  },
  {
    id: 47,
    text: 'Ordena los comportamientos EQ empezando por el que MÁS se asemeje a tu manera de actuar (bloque 2):\nA) Soy optimista en cuanto al futuro\nB) Me siento bien conmigo mismo\nC) Puedo en todo momento mantener mis emociones bajo control\nD) Sé cómo enfrentar los problemas más desagradables\nE) Los demás piensan que tengo firmeza y soy una persona que se hace valer',
    options: [
      'C → A → B → D → E (Control emocional, Optimismo, Bienestar propio, Enfrentar problemas, Firmeza)',
      'E → D → C → B → A (Firmeza, Problemas, Control, Bienestar, Optimismo)',
      'A → B → C → D → E (Optimismo, Bienestar, Control, Problemas, Firmeza)',
      'B → E → A → C → D (Bienestar, Firmeza, Optimismo, Control, Problemas)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = C → A → B → D → E. Mantener emociones bajo control es primordial; el optimismo y el bienestar propio son pilares del EQ; saber enfrentar problemas y proyectar firmeza son habilidades de apoyo.',
  },
  {
    id: 48,
    text: 'En el bloque EQ aparece la afirmación: "Nunca digo mentiras". ¿Cuál es la respuesta más honesta y adecuada?',
    options: [
      'Siempre es mi caso',
      'Pocas veces es mi caso',
      'Muchas veces es mi caso',
      'Nunca es mi caso',
    ],
    correctIndex: 1,
    explanation: 'RESPUESTA = Pocas veces es mi caso. Somos humanos y cometemos errores; afirmar "siempre" sería poco creíble y podría indicar baja autoconciencia. Reconocer que ocurre pocas veces muestra honestidad realista.',
  },
  {
    id: 49,
    text: 'Ordena los comportamientos EQ empezando por el que MÁS se asemeje a tu manera de actuar (bloque 3):\nA) En general, espero que me ocurran más cosas buenas que malas\nB) Soy capaz de comprender cómo se sienten los demás\nC) Cuando estoy en desacuerdo con alguien soy capaz de decírselo\nD) Tengo buen carácter\nE) Me caracterizo por ser una persona afectuosa',
    options: [
      'E → B → D → A → C (Afectuoso, Empatía, Carácter, Optimismo, Asertivo)',
      'A → B → C → D → E (Optimismo, Empatía, Asertivo, Carácter, Afectuoso)',
      'D → E → A → B → C (Carácter, Afectuoso, Optimismo, Empatía, Asertivo)',
      'C → A → E → B → D (Asertivo, Optimismo, Afectuoso, Empatía, Carácter)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = E → B → D → A → C. El afecto refleja extroversión y calidez; la empatía y el buen carácter complementan el servicio; el optimismo y la asertividad cierran el perfil emocional ideal.',
  },
  {
    id: 50,
    text: 'En el bloque EQ aparece la afirmación: "Obedezco las leyes incluso cuando sé que no me van a descubrir". ¿Cuál es la respuesta más adecuada?',
    options: [
      'Siempre es mi caso',
      'Pocas veces es mi caso',
      'Muchas veces es mi caso',
      'Nunca es mi caso',
    ],
    correctIndex: 2,
    explanation: 'RESPUESTA = Muchas veces es mi caso. Hay leyes que todos hemos infringido alguna vez (como pasarse un semáforo). Decir "siempre" puede sonar poco creíble; "muchas veces" muestra honestidad con madurez.',
  },
  {
    id: 51,
    text: 'Ordena los comportamientos EQ empezando por el que MÁS se asemeje a tu manera de actuar (bloque 4):\nA) Soy capaz de respetar a los demás\nB) No soy impulsivo\nC) Sé cómo mantener la calma en situaciones difíciles\nD) En tiempos difíciles, suelo esperar lo mejor\nE) Prefiero un trabajo donde tenga completa autonomía en la organización de mis actividades',
    options: [
      'A → C → B → D → E (Respeto, Calma, Control impulsivo, Optimismo, Autonomía)',
      'E → D → C → B → A (Autonomía, Optimismo, Calma, Control, Respeto)',
      'B → A → D → E → C (Control, Respeto, Optimismo, Autonomía, Calma)',
      'C → B → A → E → D (Calma, Control, Respeto, Autonomía, Optimismo)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → C → B → D → E. Respetar a los demás es la base de las relaciones laborales; mantener la calma y no ser impulsivo son claves en atención al cliente; el optimismo ante dificultades y la autonomía cierran el perfil.',
  },
  {
    id: 52,
    text: 'Ordena los comportamientos EQ empezando por el que MÁS se asemeje a tu manera de actuar (bloque 5):\nA) Me responsabilizo por mis errores\nB) Me resulta fácil hacer amigos\nC) Trato de continuar y desarrollar mis habilidades en las cosas que me divierten\nD) Busco apoyo cuando enfrento situaciones estresantes\nE) No soy una persona que exagera las cosas',
    options: [
      'B → A → E → D → C (Hacer amigos, Responsabilidad, No exagerar, Buscar apoyo, Desarrollar habilidades)',
      'A → C → B → E → D (Responsabilidad, Desarrollar, Amigos, No exagerar, Apoyo)',
      'E → D → A → B → C (No exagerar, Apoyo, Responsabilidad, Amigos, Desarrollar)',
      'D → B → C → A → E (Apoyo, Amigos, Desarrollar, Responsabilidad, No exagerar)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = B → A → E → D → C. Hacer amigos fácilmente refleja extroversión; responsabilizarse de los errores muestra madurez; no exagerar refleja equilibrio emocional; buscar apoyo es inteligencia emocional y desarrollar habilidades es crecimiento.',
  },
  {
    id: 53,
    text: 'Ordena los comportamientos EQ empezando por el que MÁS se asemeje a tu manera de actuar (bloque 6):\nA) Considero que es muy importante ser un ciudadano que acata las normas\nB) Me resulta fácil decir no cuando tengo el deseo de hacerlo\nC) Me considero una persona animada\nD) Soy bueno para comprender los sentimientos de las personas\nE) Soy paciente',
    options: [
      'C → D → E → A → B (Animado, Comprender sentimientos, Paciente, Normas, Asertividad)',
      'A → C → D → E → B (Normas, Animado, Comprender, Paciente, Asertividad)',
      'E → B → A → D → C (Paciente, Asertividad, Normas, Comprender, Animado)',
      'D → A → C → B → E (Comprender, Normas, Animado, Asertividad, Paciente)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = C → D → E → A → B. Ser animado es extroversión directa; comprender sentimientos es empatía clave en servicio; la paciencia es esencial en caja; respetar normas muestra responsabilidad y la asertividad cierra.',
  },
  {
    id: 54,
    text: 'Ordena los comportamientos EQ empezando por el que MÁS se asemeje a tu manera de actuar (bloque 7):\nA) Me gusta ayudar a la gente\nB) Soy una persona bastante alegre y optimista\nC) Me esfuerzo por mantener una buena salud física y mental\nD) Me resulta fácil tomar decisiones por mí mismo\nE) En general, me resulta fácil realizar cambios en mi vida cotidiana',
    options: [
      'A → B → E → C → D (Ayudar, Alegre/optimista, Adaptación al cambio, Salud, Decisiones)',
      'B → A → D → C → E (Alegre, Ayudar, Decisiones, Salud, Cambio)',
      'D → E → A → B → C (Decisiones, Cambio, Ayudar, Alegre, Salud)',
      'C → A → B → E → D (Salud, Ayudar, Alegre, Cambio, Decisiones)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → E → C → D. Ayudar a la gente es el perfil de servicio; ser alegre y optimista es extroversión pura; la facilidad para el cambio muestra adaptabilidad; cuidar la salud y tomar decisiones propias son habilidades personales.',
  },
  {
    id: 55,
    text: 'En el bloque EQ aparece la afirmación: "Nunca he sentido envidia de los demás". ¿Cuál es la respuesta más adecuada?',
    options: [
      'Siempre es mi caso',
      'Muchas veces es mi caso',
      'Pocas veces es mi caso',
      'Nunca es mi caso',
    ],
    correctIndex: 1,
    explanation: 'RESPUESTA = Muchas veces es mi caso. Decir "siempre es mi caso" (que nunca envidias) sería poco creíble. Reconocer que muchas veces no sientes envidia muestra honestidad con autoconciencia equilibrada.',
  },
  {
    id: 56,
    text: 'Ordena los comportamientos EQ empezando por el que MÁS se asemeje a tu manera de actuar (bloque 8):\nA) Los demás opinan que soy una persona sociable\nB) Siento que he logrado mucho en los últimos años\nC) Me gusta tener una visión general de un problema antes de intentar solucionarlo\nD) Prefiero ser líder que tener que seguir a otros',
    options: [
      'A → B → C → D (Sociable, Logros, Visión general, Liderazgo)',
      'D → A → C → B (Liderazgo, Sociable, Visión, Logros)',
      'B → D → A → C (Logros, Liderazgo, Sociable, Visión)',
      'C → A → D → B (Visión, Sociable, Liderazgo, Logros)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → C → D. Ser reconocido como sociable refleja extroversión validada por otros; haber logrado mucho muestra autoconfianza; tener visión del problema refleja inteligencia emocional; el liderazgo cierra.',
  },
  {
    id: 57,
    text: 'En el bloque EQ aparece la afirmación: "Nunca he hablado mal de alguien a sus espaldas". ¿Cuál es la respuesta más adecuada?',
    options: [
      'Siempre es mi caso',
      'Pocas veces es mi caso',
      'Muchas veces es mi caso',
      'Nunca es mi caso',
    ],
    correctIndex: 2,
    explanation: 'RESPUESTA = Muchas veces es mi caso. Sería poco honesto decir que nunca lo has hecho. Reconocer que "muchas veces" no hablas mal demuestra honestidad y autoconciencia sin caer en la mentira social.',
  },
  {
    id: 58,
    text: 'Ordena los comportamientos EQ empezando por el que MÁS se asemeje a tu manera de actuar (bloque 9):\nA) Me siento feliz con el tipo de persona que soy\nB) Mis amigos me confían sus intimidades\nC) Sé exactamente para qué soy bueno\nD) No me resulta difícil ser realista\nE) Puedo soportar muy bien el estrés',
    options: [
      'B → A → E → C → D (Confianza de amigos, Feliz con uno mismo, Manejo estrés, Autoconocimiento, Realismo)',
      'A → C → B → D → E (Feliz, Autoconocimiento, Confianza amigos, Realismo, Estrés)',
      'E → D → C → B → A (Estrés, Realismo, Autoconocimiento, Confianza, Feliz)',
      'C → B → A → E → D (Autoconocimiento, Confianza, Feliz, Estrés, Realismo)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = B → A → E → C → D. Que los amigos confíen sus intimidades refleja empatía y extroversión; sentirse bien consigo mismo es autoestima; manejar el estrés es EQ en acción; el autoconocimiento y el realismo completan el perfil.',
  },
  {
    id: 59,
    text: 'Ordena los comportamientos EQ empezando por el que MÁS se asemeje a tu manera de actuar (bloque 10):\nA) Me es difícil ver sufrir a la gente\nB) Mantengo buenas relaciones con los demás\nC) Creo en mi capacidad para manejar los problemas más difíciles\nD) En general, me resulta fácil adaptarme\nE) Cuando comienzo algo nuevo tengo la sensación de que voy a triunfar en ello',
    options: [
      'A → B → E → D → C (Empatía al sufrimiento, Buenas relaciones, Confianza en éxito, Adaptabilidad, Capacidad)',
      'B → A → C → D → E (Relaciones, Empatía, Capacidad, Adaptabilidad, Éxito)',
      'E → C → B → A → D (Éxito, Capacidad, Relaciones, Empatía, Adaptabilidad)',
      'D → B → A → C → E (Adaptabilidad, Relaciones, Empatía, Capacidad, Éxito)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → E → D → C. La empatía ante el sufrimiento ajeno es uno de los rasgos más valorados en servicio al cliente; mantener buenas relaciones es extroversión aplicada; la confianza en el éxito, adaptabilidad y capacidad cierran el perfil EQ.',
  },

  // ─────────────────────────────────────────────
  // MÓDULO 6: PERSONALIDAD
  // ─────────────────────────────────────────────
  {
    id: 60,
    text: 'Ordena los comportamientos de Personalidad empezando por el que MÁS se asemeje a tu manera de actuar (bloque 1):\nA) Puedo controlar mis emociones para tomar decisiones\nB) Me adapto con facilidad a situaciones nuevas\nC) Soy perfeccionista y quiero que todo salga bien\nD) Creo en priorizar la diversión y la felicidad\nE) Prefiero ser autónomo antes que depender de otros',
    options: [
      'A → B → C → D → E (Control emocional, Adaptación, Perfeccionismo, Diversión, Autonomía)',
      'D → E → A → B → C (Diversión, Autonomía, Control, Adaptación, Perfeccionismo)',
      'C → A → B → E → D (Perfeccionismo, Control, Adaptación, Autonomía, Diversión)',
      'E → C → D → A → B (Autonomía, Perfeccionismo, Diversión, Control, Adaptación)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → C → D → E. El autocontrol emocional es esencial en caja; la adaptabilidad refleja el perfil flexible que busca Corp Favorita; el perfeccionismo muestra calidad; la diversión refleja extroversión y la autonomía cierra.',
  },
  {
    id: 61,
    text: 'Ordena los comportamientos de Personalidad empezando por el que MÁS se asemeje a tu manera de actuar (bloque 2):\nA) Priorizo las normas sobre la libertad personal\nB) Me siento cómodo tomando decisiones importantes\nC) Mantengo la calma bajo presión\nD) No necesito la aprobación de los demás para decidir\nE) Salgo frecuentemente a actividades de entretenimiento',
    options: [
      'C → A → B → E → D (Calma bajo presión, Normas, Decisiones, Entretenimiento, Autonomía decisión)',
      'E → D → C → B → A (Entretenimiento, Autonomía, Calma, Decisiones, Normas)',
      'A → C → D → B → E (Normas, Calma, Autonomía, Decisiones, Entretenimiento)',
      'B → E → A → D → C (Decisiones, Entretenimiento, Normas, Autonomía, Calma)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = C → A → B → E → D. Mantener la calma bajo presión es primordial en el perfil de cajero; respetar normas muestra responsabilidad; tomar decisiones importantes refleja confianza; las salidas de entretenimiento muestran extroversión y la autonomía cierra.',
  },
  {
    id: 62,
    text: 'Ordena los comportamientos de Personalidad empezando por el que MÁS se asemeje a tu manera de actuar (bloque 3):\nA) Tomo decisiones basándome en principios morales\nB) Me apasiona aprender cosas nuevas\nC) Disfruto contando historias divertidas\nD) Disfruto tomando la iniciativa en proyectos y actividades\nE) Prefiero trabajar en solitario cuando es posible',
    options: [
      'C → D → A → B → E (Historias divertidas, Iniciativa, Principios morales, Aprender, Solitario)',
      'E → A → B → C → D (Solitario, Moral, Aprender, Historias, Iniciativa)',
      'A → C → D → B → E (Moral, Historias, Iniciativa, Aprender, Solitario)',
      'B → E → C → D → A (Aprender, Solitario, Historias, Iniciativa, Moral)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = C → D → A → B → E. Contar historias divertidas refleja extroversión y sociabilidad; tomar la iniciativa muestra liderazgo activo; los principios morales revelan ética; la pasión por aprender es crecimiento; trabajar en solitario va al final pues Corp Favorita busca perfiles de equipo.',
  },
  {
    id: 63,
    text: 'Ordena los comportamientos de Personalidad empezando por el que MÁS se asemeje a tu manera de actuar (bloque 4):\nA) Las actividades sociales me llenan de energía\nB) Sigo las reglas incluso en circunstancias adversas\nC) Manejo urgencias con calma\nD) Disfruto explorando nuevas ideas y conceptos\nE) Confío en resolver problemas sin ayuda externa',
    options: [
      'A → C → B → D → E (Social/energía, Calma urgencias, Normas, Explorar ideas, Autonomía)',
      'E → D → A → C → B (Autonomía, Explorar, Social, Calma, Normas)',
      'B → A → C → E → D (Normas, Social, Calma, Autonomía, Explorar)',
      'C → B → E → A → D (Calma, Normas, Autonomía, Social, Explorar)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → C → B → D → E. Las actividades sociales que dan energía son la máxima expresión de extroversión; manejar urgencias con calma es clave en caja; seguir normas muestra responsabilidad; explorar ideas y autonomía son complementos.',
  },
  {
    id: 64,
    text: 'Ordena los comportamientos de Personalidad empezando por el que MÁS se asemeje a tu manera de actuar (bloque 5):\nA) Mantengo el control en situaciones difíciles\nB) Si fracaso, vuelvo a intentarlo hasta lograrlo\nC) Disfruto más las fiestas animadas que pasar tiempo a solas\nD) Disfruto aprendiendo sobre otras culturas y países\nE) Planifico mi vida meticulosamente',
    options: [
      'C → A → B → E → D (Fiestas/sociabilidad, Control, Perseverancia, Planificación, Culturas)',
      'A → B → C → D → E (Control, Perseverancia, Fiestas, Culturas, Planificación)',
      'E → C → A → B → D (Planificación, Fiestas, Control, Perseverancia, Culturas)',
      'B → A → D → C → E (Perseverancia, Control, Culturas, Fiestas, Planificación)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = C → A → B → E → D. Preferir fiestas animadas es extroversión explícita; mantener control es estabilidad emocional; la perseverancia muestra compromiso; la planificación refleja organización y el interés cultural es apertura cognitiva.',
  },
  {
    id: 65,
    text: 'Ordena los comportamientos de Personalidad empezando por el que MÁS se asemeje a tu manera de actuar (bloque 6):\nA) Disfruto compartiendo recuerdos sociales con amigos\nB) Me siento cómodo adaptándome a cambios y situaciones inesperadas\nC) Soy perfeccionista\nD) Me gusta tener el control en situaciones difíciles\nE) Prefiero tomar mis propias decisiones',
    options: [
      'A → B → D → C → E (Recuerdos sociales, Adaptación, Control situaciones, Perfeccionismo, Autonomía)',
      'C → E → A → D → B (Perfeccionismo, Autonomía, Social, Control, Adaptación)',
      'D → A → B → E → C (Control, Social, Adaptación, Autonomía, Perfeccionismo)',
      'E → C → D → B → A (Autonomía, Perfeccionismo, Control, Adaptación, Social)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → D → C → E. Compartir recuerdos sociales es extroversión en acción; adaptarse a cambios es flexibilidad valorada; controlar situaciones difíciles es madurez; el perfeccionismo y la autonomía van al final.',
  },
  {
    id: 66,
    text: 'Ordena los comportamientos de Personalidad empezando por el que MÁS se asemeje a tu manera de actuar (bloque 7):\nA) Me consideran una persona sociable y cercana\nB) Pienso antes de actuar\nC) Exploro nuevas ideas con entusiasmo\nD) Me siento insatisfecho si no se cuidan todos los detalles',
    options: [
      'A → C → B → D (Sociable/cercano, Explorar ideas, Reflexivo, Perfeccionismo en detalles)',
      'D → B → A → C (Detalles, Reflexivo, Sociable, Explorar)',
      'B → A → D → C (Reflexivo, Sociable, Detalles, Explorar)',
      'C → D → A → B (Explorar, Detalles, Sociable, Reflexivo)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → C → B → D. Ser sociable y cercano es el perfil extrovertido ideal; explorar ideas con entusiasmo refleja apertura; pensar antes de actuar muestra reflexión; la insatisfacción por detalles es perfeccionismo que va al final.',
  },
  {
    id: 67,
    text: 'Ordena los comportamientos de Personalidad empezando por el que MÁS se asemeje a tu manera de actuar (bloque 8):\nA) Manejo conflictos con serenidad\nB) Me resulta fácil persuadir a los demás\nC) Mantengo mis cosas en perfecto estado\nD) Suelo encontrar soluciones por mi cuenta\nE) Me gusta entretener a los invitados',
    options: [
      'E → A → B → C → D (Entretener, Serenidad, Persuadir, Orden, Autonomía)',
      'A → E → D → B → C (Serenidad, Entretener, Autonomía, Persuadir, Orden)',
      'B → D → E → A → C (Persuadir, Autonomía, Entretener, Serenidad, Orden)',
      'C → B → A → E → D (Orden, Persuadir, Serenidad, Entretener, Autonomía)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = E → A → B → C → D. Entretener a los invitados es extroversión social; manejar conflictos con serenidad es estabilidad emocional; persuadir muestra habilidad interpersonal; el orden y la autonomía cierran el perfil.',
  },
  {
    id: 68,
    text: 'Ordena los comportamientos de Personalidad empezando por el que MÁS se asemeje a tu manera de actuar (bloque 9):\nA) La gente me considera un buen conversador\nB) Cumplo las normas, aunque pueda evadirlas\nC) Me siento cómodo trabajando de forma independiente\nD) En los grupos de trabajo, prefiero asumir el rol de líder\nE) Valoro el conocimiento histórico',
    options: [
      'A → B → D → C → E (Buen conversador, Normas, Liderazgo, Independencia, Conocimiento histórico)',
      'D → A → B → E → C (Liderazgo, Conversador, Normas, Histórico, Independencia)',
      'B → D → A → C → E (Normas, Liderazgo, Conversador, Independencia, Histórico)',
      'C → E → A → D → B (Independencia, Histórico, Conversador, Liderazgo, Normas)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → D → C → E. Ser buen conversador es la extroversión aplicada al servicio; cumplir normas aunque pueda evadirlas muestra ética; el liderazgo en grupo refleja iniciativa; independencia y conocimiento histórico son complementos.',
  },
  {
    id: 69,
    text: 'Ordena los comportamientos de Personalidad empezando por el que MÁS se asemeje a tu manera de actuar (bloque 10):\nA) Me considero una persona sociable\nB) Se me da bien controlar mis expresiones emocionales\nC) Cuando empiezo algo, tengo la certeza de que lo terminaré\nD) Respeto a la autoridad y sus indicaciones\nE) Reviso varias veces antes de terminar algo',
    options: [
      'A → D → B → C → E (Sociable, Respeto autoridad, Control emocional, Certeza conclusión, Revisión)',
      'E → C → A → B → D (Revisión, Certeza, Sociable, Control, Respeto)',
      'B → A → D → E → C (Control, Sociable, Respeto, Revisión, Certeza)',
      'D → A → C → B → E (Respeto, Sociable, Certeza, Control, Revisión)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → D → B → C → E. La sociabilidad es el rasgo más alineado con el perfil de Corp Favorita; respetar la autoridad muestra compromiso con la empresa; el control emocional es esencial; la certeza al terminar y la revisión cierran el perfil de calidad.',
  },
  {
    id: 70,
    text: 'Ordena los comportamientos de Personalidad empezando por el que MÁS se asemeje a tu manera de actuar (bloque 11):\nA) Mantengo la calma en la mayoría de situaciones\nB) Valoro la honestidad ante todo\nC) Soy una persona con mucha energía\nD) Si algo no se desarrolla rápido, persisto hasta conseguirlo\nE) Me fascinan las culturas diferentes',
    options: [
      'C → A → B → D → E (Energía, Calma, Honestidad, Persistencia, Culturas)',
      'B → A → C → E → D (Honestidad, Calma, Energía, Culturas, Persistencia)',
      'A → C → D → B → E (Calma, Energía, Persistencia, Honestidad, Culturas)',
      'D → B → C → A → E (Persistencia, Honestidad, Energía, Calma, Culturas)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = C → A → B → D → E. La energía refleja extroversión y disposición activa; la calma muestra estabilidad emocional; la honestidad es un valor ético clave; la persistencia muestra compromiso y el interés por culturas es apertura cognitiva.',
  },
  {
    id: 71,
    text: 'Ordena los comportamientos de Personalidad empezando por el que MÁS se asemeje a tu manera de actuar (bloque 12):\nA) Mantengo la calma en situaciones estresantes\nB) Respeto las normas en todo momento\nC) Me gusta revisar mi trabajo para evitar errores\nD) Me esfuerzo por ser amable y considerado con los demás\nE) Suelo corregir a los demás cuando se equivocan',
    options: [
      'D → A → B → C → E (Amable/considerado, Calma estrés, Normas, Revisar trabajo, Corregir)',
      'A → D → B → E → C (Calma, Amable, Normas, Corregir, Revisar)',
      'B → C → D → A → E (Normas, Revisar, Amable, Calma, Corregir)',
      'E → B → A → D → C (Corregir, Normas, Calma, Amable, Revisar)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = D → A → B → C → E. Ser amable y considerado es el perfil de servicio extrovertido; la calma en estrés es fundamental en caja; respetar normas muestra ética; revisar el trabajo refleja calidad y corregir a otros va al final para no parecer autoritario.',
  },
  {
    id: 72,
    text: 'Ordena los comportamientos de Personalidad empezando por el que MÁS se asemeje a tu manera de actuar (bloque 13):\nA) Soy amable incluso con desconocidos\nB) Cedo cuando es necesario para el equipo\nC) Expreso mis emociones abiertamente\nD) Me gusta revisar todo hasta el mínimo detalle\nE) Dedico mucho tiempo a la lectura',
    options: [
      'A → C → B → D → E (Amable con desconocidos, Emociones abiertas, Ceder al equipo, Revisar detalles, Lectura)',
      'E → D → A → B → C (Lectura, Detalles, Amable, Ceder, Emociones)',
      'B → A → D → C → E (Ceder, Amable, Detalles, Emociones, Lectura)',
      'D → C → A → E → B (Detalles, Emociones, Amable, Lectura, Ceder)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → C → B → D → E. Ser amable incluso con desconocidos es extroversión de servicio; expresar emociones abiertamente muestra autenticidad; ceder al equipo refleja trabajo colaborativo; los detalles y la lectura son rasgos de apoyo.',
  },
  {
    id: 73,
    text: 'Ordena los comportamientos de Personalidad empezando por el que MÁS se asemeje a tu manera de actuar (bloque 14):\nA) Me siento cómodo en grupos grandes\nB) Hago sentir bienvenida a la gente\nC) Me resulta fácil controlar mis impulsos\nD) Me gusta que mi trabajo sea impecable\nE) Valoro las opiniones de mis compañeros',
    options: [
      'B → A → E → C → D (Bienvenida a gente, Grupos grandes, Opiniones compañeros, Control impulsos, Trabajo impecable)',
      'A → B → C → E → D (Grupos, Bienvenida, Control, Opiniones, Impecable)',
      'D → C → B → A → E (Impecable, Control, Bienvenida, Grupos, Opiniones)',
      'E → B → A → D → C (Opiniones, Bienvenida, Grupos, Impecable, Control)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = B → A → E → C → D. Hacer sentir bienvenida a la gente es el servicio extrovertido en su máxima expresión; sentirse cómodo en grupos grandes es extroversión pura; valorar opiniones muestra trabajo en equipo; el control de impulsos y el trabajo impecable cierran.',
  },
  {
    id: 74,
    text: 'Ordena los comportamientos de Personalidad empezando por el que MÁS se asemeje a tu manera de actuar (bloque 15):\nA) Soy comunicativo\nB) Tomo la iniciativa en situaciones sociales\nC) Ayudo a otros sin esperar nada a cambio\nD) Reviso trabajos minuciosamente al terminarlos\nE) Me interesan temas científicos y filosóficos',
    options: [
      'A → B → C → D → E (Comunicativo, Iniciativa social, Ayudar sin esperar, Revisar, Científico/filosófico)',
      'E → D → A → B → C (Científico, Revisar, Comunicativo, Iniciativa, Ayudar)',
      'C → A → B → E → D (Ayudar, Comunicativo, Iniciativa, Científico, Revisar)',
      'B → C → D → A → E (Iniciativa, Ayudar, Revisar, Comunicativo, Científico)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → B → C → D → E. Ser comunicativo es la base de la extroversión; tomar iniciativa social refleja liderazgo relacional; ayudar sin esperar nada muestra vocación de servicio; revisar trabajos es calidad y los intereses científicos cierran como rasgo intelectual.',
  },
  {
    id: 75,
    text: 'Ordena los comportamientos de Personalidad empezando por el que MÁS se asemeje a tu manera de actuar (bloque 16):\nA) Disfruto colaborar con los demás\nB) Me mantengo sereno en situaciones molestas\nC) Me gusta mantener todo en orden\nD) Soy paciente con los demás\nE) Disfruto programas culturales y científicos',
    options: [
      'A → D → B → C → E (Colaborar, Paciencia con otros, Serenidad, Orden, Programas culturales)',
      'C → B → A → E → D (Orden, Serenidad, Colaborar, Cultural, Paciencia)',
      'B → A → D → E → C (Serenidad, Colaborar, Paciencia, Cultural, Orden)',
      'D → C → E → A → B (Paciencia, Orden, Cultural, Colaborar, Serenidad)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = A → D → B → C → E. Colaborar con los demás es trabajo en equipo; la paciencia con otros refleja el perfil de servicio; la serenidad es estabilidad emocional en caja; el orden es organización personal y los programas culturales cierran.',
  },
  {
    id: 76,
    text: 'Ordena los comportamientos de Personalidad empezando por el que MÁS se asemeje a tu manera de actuar (bloque 17):\nA) Prefiero trabajar en equipo\nB) Me considero una persona muy amable\nC) Cumplo mis compromisos puntualmente\nD) Me siento cómodo al hablar en público\nE) Me encanta discutir sobre películas y libros',
    options: [
      'B → D → A → C → E (Amable, Hablar en público, Equipo, Puntualidad, Debates culturales)',
      'A → C → B → E → D (Equipo, Puntualidad, Amable, Debates, Hablar público)',
      'D → B → C → A → E (Hablar público, Amable, Puntualidad, Equipo, Debates)',
      'C → A → D → B → E (Puntualidad, Equipo, Hablar público, Amable, Debates)',
    ],
    correctIndex: 0,
    explanation: 'ORDEN = B → D → A → C → E. Ser muy amable es el perfil de servicio de Corp Favorita; sentirse cómodo hablando en público es extroversión aplicada; preferir el equipo refleja colaboración; la puntualidad muestra responsabilidad y los debates culturales cierran.',
  },
];